load('dfWaterFlow.RData')
load('dfWFPC.RData')
country_code <- read.csv("country_code.csv")

library(dplyr)
library(tidyr)
library(plotly)
library(shiny)
library(DT)
library(shinyBS)
# install.packages("leaflet")
# install.packages("rgdal")
